# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Warning_window(object):
    def setupUi(self, Warning_window):
        Warning_window.setObjectName("Warning_window")
        Warning_window.setEnabled(True)
        Warning_window.resize(232, 205)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        Warning_window.setPalette(palette)
        Warning_window.setAutoFillBackground(True)
        self.pushButton = QtWidgets.QPushButton(Warning_window)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(70, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Warning_window)
        self.label.setGeometry(QtCore.QRect(20, 0, 191, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Warning_window)
        self.pushButton.clicked.connect(Warning_window.close)
        QtCore.QMetaObject.connectSlotsByName(Warning_window)

    def retranslateUi(self, Warning_window):
        _translate = QtCore.QCoreApplication.translate
        Warning_window.setWindowTitle(_translate("Warning_window", "Warning!"))
        self.pushButton.setText(_translate("Warning_window", "OK"))
        self.label.setText(_translate("Warning_window", "На сайте нет столько страниц"))
